version: 2
jobs:
  build:
    docker:
      - image: python
    working_directory: ~/docSite
    steps:
      - checkout
      - run:
          name: Install mkdocs
          command: pip install mkdocs
      - run:
          name: Pip Install AWS CLI
          command: pip install awscli
      - run:
          name: build site
          command: mkdocs build
      - run:
          name: Push to S3 bucket
          command: cd site/ && aws s3 sync . s3://mkdocs-casual-urchin --region eu-west-1 --acl public-read
